AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-deletion


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ImageDeletionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: image_deletion/
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          S3_ENDPOINT: ""
      Events:
        ImageDeletion:
          Type: SQS
          Properties:
            Queue: !GetAtt SrcQueue.Arn
            BatchSize: 10
  SrcQueue:
    Type: AWS::SQS::Queue

  

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   MaskingCreationApi:
#     Description: "API Gateway endpoint URL for Prod stage for Masking Creation function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/defailt/masking/"
#     MaskingCreationFunction:
#     Description: "Masking Creation Lambda Function ARN"
#     Value: !GetAtt MaskingCreationFunction.Arn
#     MaskingCreationFunctionIamRole:
#     Description: "Implicit IAM Role created for Masking Creation function"
#     Value: !GetAtt MaskingCreationRole.Arn
